version: "3.2"  # optional since v1.27.0
services:
  fern-definition-registry:
    image: fern-definition-registry:local
    ports:
      - 8080:8080
    environment: 
      VENUS_URL: dummy
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: fern
  s3-mock:
    image: adobe/s3mock
    ports:
      - 9090:9090
      - 9191:9191
    environment:
      initialBuckets: fdr