version: 2.1
orbs:
  node: circleci/node@5.0.1
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  check:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: fern generate --log-level debug
      - run:
          command: yarn compile
          name: Compile
      - run:
          command: yarn format:check
          name: Check formatting
      - run:
          command: yarn lint
          name: Lint
      - run:
          command: yarn test
          name: Test

  deploy-dev:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run compile
          name: Compile
      - aws-cli/setup
      - run:
          command: yarn run dev:db:migrate
          name: prisma deploy
      - run:
          command: |
            git_version="$(scripts/git-version.sh)"
            yarn run dev:docker "${git_version}"
            npm install -g aws-cdk
            cd fdr-deploy
            npm install
            VERSION="${git_version}" cdk deploy fdr-dev --require-approval never --progress events
          name: cdk deploy

workflows:
  version: 2
  build:
    jobs:
      - check:
          filters:
            tags:
              only: /.*/
          context:
            - fern-tokens

      - deploy-dev:
          requires: [check]
          filters:
            branches:
              only:
                - main
          context:
            - aws
            - github
            - fern-dev
            - fern-tokens
