name: fern-definition-registry-api
definition: src
generators:
  - name: fernapi/fern-typescript
    version: 0.0.155
    generate: true
    config:
      mode: server
  - name: fernapi/fern-postman
    version: 0.0.17
    generate:
      enabled: true
      output: ./generated-postman.json
    config: {}
