imports: 
  registry: registry.yml

service:
  base-path: /environments
  auth: true
  endpoints:
    getAll:
      path: ""
      method: GET
      response: GetAllEnvironmentsResponse
    
    create: 
      path: /create
      method: POST
      request: Environment
      errors: 
        - EnvironmentIdAlreadyExistsError
    
    delete: 
      path: /{environmentId}
      path-parameters:
        environmentId: EnvironmentId
      method: DELETE
      errors: 
        - EnvironmentDoesNotExistError

types:
  EnvironmentId: uuid

  Environment:
    properties:
      id: EnvironmentId
      name: string
      url: string

  GetAllEnvironmentsResponse:
    properties:
      environments: list<Environment>

errors:
  EnvironmentDoesNotExistError:
    status-code: 404
  
  EnvironmentIdAlreadyExistsError: 
    status-code: 400
