# yaml-language-server: $schema=https://raw.githubusercontent.com/fern-api/fern/main/fern.schema.json

imports:
  type: type.yml

types:
  ServiceDefinition:
    properties:
      name: string
      endpoints: list<Endpoint>

  Endpoint:
    properties:
      path: EndpointPath
      request: optional<type.TypeReference>
      response: optional<type.TypeReference>

  EndpointPath:
    properties:
      parts: list<EndpointPathPart>

  EndpointPathPart:
    union:
      literal: string
      pathParameter: EndpointPathParameter

  EndpointPathParameter:
    properties:
      name: string
      parameterType: type.TypeReference
