name: fern-definition-registry-api
definition: src
generators: 
  java:
    version: 0.0.155
    config:
      mode: server
  typescript: 
    version: 0.0.155
    config:
      mode: client
  postman: 
    version: 0.0.17
    config:
      api-key: ${POSTMAN_API_KEY}
      workspace-id: ${POSTMAN_WORKSPACE_ID} 
invocations: 
  draft:
    - java
  merge: 
    - typescript
  release:
    - postman